### ISSUE TITLE
Error Json(path="object.json") : AttributeError: 'str' object has no attribute 'read'

### ISSUE THREAD

**Issue by limsan** [brennv/namedtupled#21]
Traceback (most recent call last):
  File "testNameTupled.py", line 6, in <module>
    vals = namedtupled.json(path="object.json")
  File "C:\Users\PERKASA\AppData\Local\conda\conda\envs\python2\lib\site-packages\namedtupled\integrations.py", line 19, in load_json
    return mapper(json.load(path), _nt_name=name)
  File "C:\Users\PERKASA\AppData\Local\conda\conda\envs\python2\lib\json\__init__.py", line 287, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'

**Comment by jonseymour** [comment]
@limsan  the confusion, I think, is that the path parameter (in the definition of namedtupled.json) is misnamed. In practice, it is actually meant to be file-like argument of the same type expected by json.load() rather than the name of file as per your (reasonable) expectation.

**Comment by brennv** [comment]
Looking back at this again, sorry I'm still thinking about the best way forward
